In [2]:
import numpy as np

In [3]:
pyList= [1,2]
pyList

[1, 2]

In [4]:
pyList * 2

[1, 2, 1, 2]

In [8]:
arr = np.arange(0,10)
arr2 = np.copy(arr)

Operations

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
1/arr

/var/folders/2x/rlw253810934sxx39r2nh1s80000gn/T/ipykernel_55819/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
print(arr + arr2)
print(arr / arr2)
print(arr * arr2)

[ 0  2  4  6  8 10 12 14 16 18]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0  1  4  9 16 25 36 49 64 81]


/var/folders/2x/rlw253810934sxx39r2nh1s80000gn/T/ipykernel_55819/3782071510.py:2: RuntimeWarning: invalid value encountered in divide
  print(arr / arr2)


In [20]:
matrix = arr.reshape(2,5)
matrix2 = matrix.copy()


In [22]:
print(matrix + matrix2)
print(matrix - matrix2)
print(matrix * matrix2)
print(matrix / matrix2)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[ 0  1  4  9 16]
 [25 36 49 64 81]]
[[nan  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


/var/folders/2x/rlw253810934sxx39r2nh1s80000gn/T/ipykernel_55819/1758944796.py:4: RuntimeWarning: invalid value encountered in divide
  print(matrix / matrix2)


In [25]:
# mat multiplications
print(np.matmul(matrix,matrix2.T))
print(matrix @ matrix2.T)

[[ 30  80]
 [ 80 255]]
[[ 30  80]
 [ 80 255]]
