In [12]:
import numpy as np

In [21]:
pyList = [2,4,6,8,10,12,14,16,18,20]
pyList

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

Convert a python list to np array

In [24]:
npArray = np.array(pyList)
print(npArray)
print(type(npArray))

[ 2  4  6  8 10 12 14 16 18 20]
<class 'numpy.ndarray'>


In [15]:
#  npArray has Two dimensions
pyMatrix = [[1,2,3],[4,5,6],[7,8,9]]
npMatrix= np.array(pyMatrix)

print(pyMatrix)
print(npMatrix, type(npMatrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [33]:
# slicing matrix
npMatrix[0:3]

#slicing array
npArray[2:]

array([ 6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
# all data by step
npArray[::3]

array([ 2,  8, 14, 20])

In [37]:
# get the last one
npArray[-1]

np.int64(20)

In [42]:
npMatrix[1:,0:2]

array([[4, 5],
       [7, 8]])