Dim     Name
1. 0     Scalar
2. 1     Vector
3. 2     Matrix
4. 3-n   Tensor

In [8]:
import numpy as np

In [9]:
scalar = np.array(42)
print(scalar)
print(scalar.ndim)

42
0


In [7]:
vector = np.array([1,2,3])
print(vector)
print(vector.ndim)

[1 2 3]
1


In [11]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.ndim)

[[1 2 3]
 [4 5 6]]
2


In [14]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,4]],[[1,2,3],[4,5,6],[7,8,9],[0,2,4]]])
print(tensor)
print(tensor.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [0 2 4]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]
  [0 2 4]]]
3


## Adding or deleting dimensions

In [16]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
print(vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


## Adding dimensions only at one side
axis= 0  # rows
axis= 1  # cols

In [21]:
# add dimension in rows
expand= np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
print(expand.ndim)

[[1 2 3]]
2


In [24]:
# delete dimension
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
