In [1]:
import numpy as np

NumPy is a powerful Python library for numerical computations, especially when dealing with arrays. Two fundamental concepts in NumPy are shape and reshape. These concepts are essential for understanding how to manipulate the dimensions of arrays, which is a crucial part of many data processing tasks.

Here, arr1 is a 1-dimensional array with 5 elements. The shape (5,) indicates that there is 1 dimension with 5 elements.

In [2]:
# 1D array (vector)
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.shape)  # Output: (5,)

(5,)


Here, arr2 is a 2-dimensional array (matrix) with 2 rows and 3 columns. The shape (2, 3) indicates 2 dimensions: the first with 2 elements (rows), and the second with 3 elements (columns).

In [3]:
# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)  # Output: (2, 3)

(2, 3)


Here, arr3 is a 3-dimensional array. The shape (2, 2, 2) indicates 3 dimensions: each dimension has 2 elements.

In [4]:
# 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3.shape)  # Output: (2, 2, 2)

(2, 2, 2)


## 2. reshape Method in NumPy

The reshape method is used to change the shape of an existing array without changing its data. You can reshape an array to any shape that is compatible with its original shape. This means that the total number of elements must remain the same.

new_shape: A tuple defining the new shape you want to give the array.
array.reshape(new_shape)

Here, arr1 is reshaped from a 1-dimensional array with 6 elements into a 2-dimensional array with 2 rows and 3 columns.

In [7]:
# Example 1: Reshape a 1D array into a 2D array
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = arr1.reshape((2, 3))
print(arr2)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


Here, arr2 is reshaped from a 2-dimensional array into a 1-dimensional array with 6 elements.

In [10]:
#Example 2: Reshape a 2D array into a 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = arr2.reshape((6,))
print(arr1)
# Output: [1 2 3 4 5 6]


[1 2 3 4 5 6]


	Here, a 1-dimensional array with 8 elements is reshaped into a 3-dimensional array with shape (2, 2, 2).

In [11]:
# Example 3: Reshape into a 3D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr3d = arr.reshape((2, 2, 2))
print(arr3d)
# Output:
# [[[1 2]
#   [3 4]]
#
#  [[5 6]
#   [7 8]]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Important Points to Remember:

1.	Total Number of Elements Must Match: The product of the dimensions in the new_shape must equal the total number of elements in the original array.
	• For example, an array with shape (6,) (6 elements) can be reshaped to (2, 3) (2x3=6) but not to (2, 2) (2x2=4).

2.	Automatic Dimension Calculation:
	• You can use -1 as one of the dimensions in the new_shape tuple, and NumPy will automatically calculate the size of that dimension.
	
3.	Reshape Does Not Change the Original Array:
	•	The reshape method returns a new array and does not modify the original array unless you explicitly assign it.

Here, -1 tells NumPy to figure out the correct dimension size automatically. Since the total size is 6, and one dimension is 2, the other dimension is automatically calculated to be 3.

In [12]:
# Example:
arr = np.array([1, 2, 3, 4, 5, 6])
arr2d = arr.reshape((2, -1))
print(arr2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


Practical Uses of shape and reshape:

•	Data Preparation: When preparing data for machine learning models, you often need to reshape data into the appropriate form for input into the model.

•	Matrix Operations: Matrix operations often require that arrays have specific dimensions, so reshaping is essential to ensure compatibility.

•	Image Data: Images can be represented as 3D arrays (height, width, color channels), and reshaping is necessary when preprocessing image data.

# Testing

In [13]:
arr = np.random.randint(1,10,(3,2))
print(arr)
print(arr.shape)

[[9 1]
 [3 9]
 [1 4]]
(3, 2)


In [15]:
print(arr.reshape(1,6))
print(arr.reshape(2,3))

[[9 1 3 9 1 4]]
[[9 1 3]
 [9 1 4]]


In [16]:
print(np.reshape(arr,(1,6)))

[[9 1 3 9 1 4]]


In [24]:
# how is it sort
arr

array([[9, 1],
       [3, 9],
       [1, 4]])

In [28]:
np.reshape(arr,(2,3), order="C")

array([[9, 1, 3],
       [9, 1, 4]])

In [27]:
np.reshape(arr,(2,3),order='F')

array([[9, 1, 9],
       [3, 1, 4]])

In [32]:
np.reshape(arr,(2,-1),order='A')

array([[9, 1, 3],
       [9, 1, 4]])