In [1]:
import numpy as np

In [9]:
arr= np.random.randint(1,20,10)
arr

array([18,  4,  6,  5,  5,  6, 16, 11,  2,  2])

In [12]:
matrix= arr.reshape(2,5)
matrix

array([[18,  4,  6,  5,  5],
       [ 6, 16, 11,  2,  2]])

In [22]:
print("max", arr.max())
print("min", arr.min())

max 18
min 2


In [23]:
print('max in rows', matrix.max(1))
print('max in cols', matrix.max(0))

print('min in rows', matrix.min(1))
print('min in cols', matrix.min(0))


max in rows [18 16]
max in cols [18 16 11  5  5]
min in rows [4 2]
min in cols [6 4 6 2 2]


In [24]:
# index for the max value on the whole array
print("argmax",arr.argmax())
print("argmin",arr.argmin())

argmax 0
argmin 8


In [27]:
print(matrix.argmax(0))
print(matrix.argmin(0))

[0 1 1 0 0]
[1 0 0 1 1]


In [33]:
# peak to peak
print(arr)
print(arr.max(),'-' ,arr.min())

print(np.ptp(arr))

[18  4  6  5  5  6 16 11  2  2]
18  -  2
16


In [37]:
print(matrix)
print(matrix.max(0),'-', matrix.min(0))
np.ptp(matrix,0)

[[18  4  6  5  5]
 [ 6 16 11  2  2]]
[18 16 11  5  5] - [6 4 6 2 2]


array([12, 12,  5,  3,  3])

# Stats

In [41]:
arr.sort()
arr

array([ 2,  2,  4,  5,  5,  6,  6, 11, 16, 18])

In [42]:
print(arr)
print(np.percentile(arr,50))

[ 2  2  4  5  5  6  6 11 16 18]
5.5


In [43]:
np.median(arr)

np.float64(5.5)

In [45]:
np.median(matrix,1)

array([ 4., 11.])

In [48]:
np.std(arr) ** 2

np.float64(28.449999999999996)

In [47]:
np.var(arr)

np.float64(28.45)

In [49]:
np.mean(arr)

np.float64(7.5)

In [63]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([5,6])

print(arr1.ndim, arr2.ndim)

2 1


In [64]:
arr2 = np.expand_dims(arr2,axis=0)

print(arr1.ndim, arr2.ndim)

2 2


In [65]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
np.concatenate((arr1,arr2.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])