In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr_slice = arr[0:6]

In [8]:
arr_slice[:] = 0
arr_slice

array([0, 0, 0, 0, 0, 0])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [13]:
arr_copy = arr.copy()

In [14]:
arr_copy[:]= 100

In [16]:
print(arr_copy) 
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]
[ 0  0  0  0  0  0  6  7  8  9 10]
