In [1]:
import numpy as np

In [9]:
arr= np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [10]:
condex = arr > 5
condex 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [12]:
print(arr[condex])
print(arr[arr > 5])

[ 6  7  8  9 10]
[ 6  7  8  9 10]


In [15]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [16]:
arr[arr > 5] = 99

In [17]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [18]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)